name: potagenieux
description: Display website for market gardening test

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.1"
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  google_fonts: ^2.3.1
  cloud_firestore: ^3.1.12
  firebase_auth: ^3.3.14
  firebase_storage: ^10.2.12
  firebase_core: ^1.14.1
  email_validator: ^2.0.1
  flutter_email_sender: ^5.1.0
  cached_network_image: ^3.2.0
  loading_animations: ^2.2.0
  cloud_functions: ^3.2.12
  flutter_markdown: ^0.6.10
  flutter_platform_widgets: ^1.20.0
  responsive_framework: ^0.1.7
  responsive_grid: ^2.0.0
  google_nav_bar: ^5.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/terms/

